### ISSUE TITLE
Tolerance errors when testing functions output

### ISSUE THREAD

**Issue by FedericoTartarini** [FedericoTartarini/validation-data-comfort-models#1]
@marcelschweiker I am proposing to use the following values. What do you think?
- adaptive_ashrae()
  - tmp_cmf = 0.1
- adaptive_en()
  - tmp_cmf = 0.1
- a_pmv() Adaptive Predicted Mean Vote (aPMV)
  - pmv = 0.01
- athb() Adaptive Thermal Heat Balance (ATHB)
  - athb_pmv = 0.01
- e_pmv() Adjusted Predicted Mean Votes with Expectancy Factor (ePMV)
  - pmv = 0.01
- at() [Apparent Temperature (AT)](https://pythermalcomfort.readthedocs.io/en/latest/reference/pythermalcomfort.html#apparent-temperature-at)
  - at = 0.1
- ankle_draft()
  - ppd = 0.1
- clo_tout() [Clothing prediction](https://pythermalcomfort.readthedocs.io/en/latest/reference/pythermalcomfort.html#clothing-prediction)
  - 0.01
- cooling_effect() - this is the same output of the two node-model
  - 0.01
- humidex()
  - humidex = 0.1
- heat_index()
  - 0.1
- JOS3()
  - skip testing this model
- net()
  - 0.1
- phs()
  - 't_re': 01, 
  - 'd_lim_loss_50': 1, 
  - 'd_lim_loss_95': 1, 
  - 'd_lim_t_re': 1,
  - 'water_loss': 1
  - 'w' skin wettedness: 0.02
- pet_steady()
  - 0.1
- pmv_ppd()
  - pmv = 0.01
  - ppd = 0.1
- pmv()
  - pmv = 0.01
- solar_gain()
  - 'erf': 0.1, 
  - 'delta_mrt': 0.1
- set() - this is the same output of the two node-model
  - 0.1
- two_nodes()
  - t_core:0.1
  - t_skin:0.1
  - m_rsw:0.001
  - set:0.1
  - w:0.02
- utci()
  - 0.1
- use_fans_heatwaves
  - skip this for now
- vertical_tmp_grad_ppd()
  - ppd = 0.1
- wc() - Wind chill index
  - 0.1
- discomfort_index(
  - .1 
- wbgt
  - .1

We will also need to test the psychrometric functions but we can also open a separate issue.

**Comment by marcelschweiker** [comment]
@FedericoTartarini Agree with all values.
As for two-node, I am happy to extend the outputs of R as in py. At the same time, the question is whether we need to test all output or just make sure that the final value aligns. If so, chances are high that intermediate values also align and we can save time to implement all test.
At the same time, having tests for intermediate values could help in error-detection

**Comment by FedericoTartarini** [comment]
Great so let's use these values to validate the results. I listed above the tolerance of the values I think we should test in the two-node model. @marcelschweiker please let me know what do you think. If you are happy with them we can close this issue.

In python I can only test the final values and not the intermediate ones, based on how I currently wrote the code.

**Comment by marcelschweiker** [comment]
agree with updated tolerance values. 
my reference to intermediate values were actually those that py already has as output, like t_core and t_skin, which are not original outputs of two-node model (at least for me), but more like intermediate values to calculate SET. In any case, let's align both packages' outputs
